services:
  go2rtc:
    image: alexxit/go2rtc
    # restart: unless-stopped
    network_mode: host        # WAJIB: kamera harus satu subnet/jaringan lokal
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml